/* 
 * Initiate Payment API
 *
 * Afinis is a diverse group of organizations working to support advancement and use of API standardization in the financial services industry. Utilization of this API requires a developer to [register](https://www.afinis.org/user/register) their application.
 *
 * OpenAPI spec version: 1.0.7
 * Contact: info@afinis.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;

using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace Vision.Vault.Treasury.Afnis.Model
{
    /// <summary>
    /// CreditTransferTransactionInformationInner
    /// </summary>
    [DataContract]
    public class CreditTransferTransactionInformation:  IEquatable<CreditTransferTransactionInformation>
    {

        public CreditTransferTransactionInformation()
        {
            PaymentTypeInformation = new PaymentTypeInformation();
            InstructedAmount = new InstructedAmount();
            CreditorAgent = new CreditorAgent();
            Creditor = new TransactionCreditor();
            CreditorAccount = new TransactionCreditorAccount();

        }


        /// <summary>
        /// Gets or Sets PaymentIdentification
        /// </summary>
        [DataMember(Name="paymentIdentification", EmitDefaultValue=false)]
        public string PaymentIdentification { get; set; }

        /// <summary>
        /// Gets or Sets PaymentTypeInformation
        /// </summary>
        [DataMember(Name="paymentTypeInformation", EmitDefaultValue=false)]
        public PaymentTypeInformation PaymentTypeInformation { get; set; }

        /// <summary>
        /// Gets or Sets DiscretionaryData
        /// </summary>
        [DataMember(Name="discretionaryData", EmitDefaultValue=false)]
        public DiscretionaryData DiscretionaryData { get; set; }

        /// <summary>
        /// Gets or Sets RequestedExecutionDate
        /// </summary>
        [DataMember(Name="requestedExecutionDate", EmitDefaultValue=false)]
        public string RequestedExecutionDate { get; set; }

        /// <summary>
        /// Gets or Sets SettlementTimeIndication
        /// </summary>
        [DataMember(Name="settlementTimeIndication", EmitDefaultValue=false)]
        public string SettlementTimeIndication { get; set; }

        /// <summary>
        /// Gets or Sets InstructedAmount
        /// </summary>
        [DataMember(Name="instructedAmount", EmitDefaultValue=false)]
        public InstructedAmount InstructedAmount { get; set; }

        /// <summary>
        /// Gets or Sets CreditorAgent
        /// </summary>
        [DataMember(Name="creditorAgent", EmitDefaultValue=false)]
        public CreditorAgent CreditorAgent { get; set; }

        /// <summary>
        /// Gets or Sets Creditor
        /// </summary>
        [DataMember(Name="creditor", EmitDefaultValue=false)]
        public TransactionCreditor Creditor { get; set; }

        /// <summary>
        /// Gets or Sets CreditorAccount
        /// </summary>
        [DataMember(Name="creditorAccount", EmitDefaultValue=false)]
        public TransactionCreditorAccount CreditorAccount { get; set; }

        /// <summary>
        /// Gets or Sets RemittanceInformation
        /// </summary>
        [DataMember(Name="remittanceInformation", EmitDefaultValue=false)]
        public RemittanceInformation RemittanceInformation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreditTransferTransactionInformationInner {\n");
            sb.Append("  PaymentIdentification: ").Append(PaymentIdentification).Append("\n");
            sb.Append("  PaymentTypeInformation: ").Append(PaymentTypeInformation).Append("\n");
            sb.Append("  DiscretionaryData: ").Append(DiscretionaryData).Append("\n");
            sb.Append("  RequestedExecutionDate: ").Append(RequestedExecutionDate).Append("\n");
            sb.Append("  SettlementTimeIndication: ").Append(SettlementTimeIndication).Append("\n");
            sb.Append("  InstructedAmount: ").Append(InstructedAmount).Append("\n");
            sb.Append("  CreditorAgent: ").Append(CreditorAgent).Append("\n");
            sb.Append("  Creditor: ").Append(Creditor).Append("\n");
            sb.Append("  CreditorAccount: ").Append(CreditorAccount).Append("\n");
            sb.Append("  RemittanceInformation: ").Append(RemittanceInformation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreditTransferTransactionInformation);
        }

        /// <summary>
        /// Returns true if CreditTransferTransactionInformationInner instances are equal
        /// </summary>
        /// <param name="input">Instance of CreditTransferTransactionInformationInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreditTransferTransactionInformation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PaymentIdentification == input.PaymentIdentification ||
                    (this.PaymentIdentification != null &&
                    this.PaymentIdentification.Equals(input.PaymentIdentification))
                ) && 
                (
                    this.PaymentTypeInformation == input.PaymentTypeInformation ||
                    (this.PaymentTypeInformation != null &&
                    this.PaymentTypeInformation.Equals(input.PaymentTypeInformation))
                ) && 
                (
                    this.DiscretionaryData == input.DiscretionaryData ||
                    (this.DiscretionaryData != null &&
                    this.DiscretionaryData.Equals(input.DiscretionaryData))
                ) && 
                (
                    this.RequestedExecutionDate == input.RequestedExecutionDate ||
                    (this.RequestedExecutionDate != null &&
                    this.RequestedExecutionDate.Equals(input.RequestedExecutionDate))
                ) && 
                (
                    this.SettlementTimeIndication == input.SettlementTimeIndication ||
                    (this.SettlementTimeIndication != null &&
                    this.SettlementTimeIndication.Equals(input.SettlementTimeIndication))
                ) && 
                (
                    this.InstructedAmount == input.InstructedAmount ||
                    (this.InstructedAmount != null &&
                    this.InstructedAmount.Equals(input.InstructedAmount))
                ) && 
                (
                    this.CreditorAgent == input.CreditorAgent ||
                    (this.CreditorAgent != null &&
                    this.CreditorAgent.Equals(input.CreditorAgent))
                ) && 
                (
                    this.Creditor == input.Creditor ||
                    (this.Creditor != null &&
                    this.Creditor.Equals(input.Creditor))
                ) && 
                (
                    this.CreditorAccount == input.CreditorAccount ||
                    (this.CreditorAccount != null &&
                    this.CreditorAccount.Equals(input.CreditorAccount))
                ) && 
                (
                    this.RemittanceInformation == input.RemittanceInformation ||
                    (this.RemittanceInformation != null &&
                    this.RemittanceInformation.Equals(input.RemittanceInformation))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PaymentIdentification != null)
                    hashCode = hashCode * 59 + this.PaymentIdentification.GetHashCode();
                if (this.PaymentTypeInformation != null)
                    hashCode = hashCode * 59 + this.PaymentTypeInformation.GetHashCode();
                if (this.DiscretionaryData != null)
                    hashCode = hashCode * 59 + this.DiscretionaryData.GetHashCode();
                if (this.RequestedExecutionDate != null)
                    hashCode = hashCode * 59 + this.RequestedExecutionDate.GetHashCode();
                if (this.SettlementTimeIndication != null)
                    hashCode = hashCode * 59 + this.SettlementTimeIndication.GetHashCode();
                if (this.InstructedAmount != null)
                    hashCode = hashCode * 59 + this.InstructedAmount.GetHashCode();
                if (this.CreditorAgent != null)
                    hashCode = hashCode * 59 + this.CreditorAgent.GetHashCode();
                if (this.Creditor != null)
                    hashCode = hashCode * 59 + this.Creditor.GetHashCode();
                if (this.CreditorAccount != null)
                    hashCode = hashCode * 59 + this.CreditorAccount.GetHashCode();
                if (this.RemittanceInformation != null)
                    hashCode = hashCode * 59 + this.RemittanceInformation.GetHashCode();
                return hashCode;
            }
        }

    }

}
